config/routes.rb
TimeSquirrel::Application.routes.draw do

  resources :projects
  resources :tasks
  resources :timers, :expect => [:new, :create, :index]
  resources :harvest_projects, :expect => [:new, :create]

  match "daily_total" => "home#daily", :as => :daily

  match "start_timer" => "timers#start_timer", :as => :start_timer
  match "stop_timer"  => "timers#stop_timer",  :as => :stop_timer

  match 'sync_jira_tasks' => "sync#sync_jira_tasks", :as => :sync_jira
  match 'sync_harvest_tasks' => "sync#sync_harvest_tasks", :as => :sync_harvest
  match 'push_harvest_entries' => "sync#push_harvest_entries", :as => :push_harvest_entries

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :issue_id, :summary, :project_id, :active, :harvest_task_id
  has_many :timers
  belongs_to :project
  belongs_to :harvest_task
  validate :issue_id, :summary, :presence => true

  scope :active, -> { where('active == ?', true) }
  scope :with_timers, joins(:timers).group('id')
  scope :with_timers_on_day, ->(day) { joins(:timers).where('timers.start_time >= ? and timers.start_time <= ?',day.beginning_of_day, day.end_of_day ).group('tasks.id').order('project_id') }
  scope :without_harvest_task, -> { where('harvest_task_id IS NULL')}

  delegate :api_task_id, :to => :harvest_task

  def running_timers
    timers.where("start_time IS NOT NULL and end_time IS NULL")
  end

  def project_code
    project.code
  end

  def running_timer?
    running_timers.count != 0
  end

  def start_new_timer
    stop_running_timer
    timers.create!(:start_time => Time.now)
  end

  def stop_running_timer
    return if !running_timer?
    running_timers.each do |timer|
      timer.stop
    end
  end

  def time_events_in_range(start_time, end_time)
    timers.after(start_time).before(end_time)
  end

  def total_time_in_range(start_time, end_time)
    total = 0.0
    time_events_in_range(start_time, end_time).each do |timer|
      total += timer.time_elapsed
    end

    total
  end

  def time_events_this_week
    timers.this_week
  end

  def total_time_on_day(date = Date.today)
    total = 0.0

    timers.after(date.beginning_of_day).before(date.end_of_day).each do |timer|
      total += timer.time_elapsed
    end
    total
  end

  def total_time_this_week
    total = 0.0
    time_events_this_week.each do |timer|
      total += timer.time_elapsed
    end

    total
  end

  def total_time
    total = 0.0
    timers.each do |timer|
      total += timer.time_elapsed
    end

    total
  end

  def harvest_project_tasks
    project.harvest_project.try(:harvest_tasks)
  end

  def harvest_project_api_id
    harvest_task.harvest_project.api_project_id
  end

  def classification
    harvest_task.try(:api_task_name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.active.with_timers

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new
    @harvest_tasks = HarvestTask.all.collect{ |t| ["#{t.harvest_project.api_client_name} :: #{t.api_task_name}", t.id]}

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
    @harvest_tasks = @task.harvest_project_tasks.collect{ |t| [t.api_task_name, t.id]} if @task.harvest_project_tasks.present?
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to projects_path, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    if @task.update_attributes(params[:task])
      unlinked_task = Task.without_harvest_task
      if unlinked_task.count != 0
        @task = unlinked_task.first
        redirect_to edit_task_path(@task), alert: "While you're updating tasks, here is a task that need to be associated with a Harvest Project"
      else
        redirect_to projects_path, notice: 'Task was successfully updated.'
      end
    else
      render action: "edit"
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :project_id, collection: Project.all %>
    <%= f.input :issue_id %>
    <%= f.input :summary %>
    <%= f.select :harvest_task_id, @harvest_tasks, :prompt => 'Please choose one' if @harvest_tasks %>
    <%= f.input :active %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tasks/_task_summary.html.erb
<h3><%= task.summary %> <small><%= task.project_code %>&nbsp;&nbsp;&nbsp;<%= link_to '<i class="icon-pencil"></i> '.html_safe, edit_task_path(task) %></small></h3>
<table class='table table-striped'>
  <thead>
    <tr>
      <th>Timer Start</th>
      <th>Timer End</th>
      <th>Duration</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% task.timers.each do |timer| %>
      <tr>
        <td><%= day_hour_minute(timer.start_time) %></td>
        <td><%= day_hour_minute(timer.end_time) %></td>
        <td><%= formatted_duration(timer.time_elapsed) %></td>
        <td class='task'><%= link_to '<i class="icon-pencil"></i> '.html_safe, edit_timer_path(timer) %></td>
        <td class='task'><%= link_to '<i class="icon-trash"></i> '.html_safe, timer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan='2'>
        Total
      </td>
      <td>
        <%= formatted_duration(task.total_time) %>
      </td>
      <td colspan='2'></td>
    </tr>
  </tfoot>

</table>
<%= link_to 'Manual Timer', new_timer_path, :class =>'btn btn-mini' %> <br><br>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<% @tasks.each do |task| %>
  <%= render partial: "task_summary", :locals => { :task => task } %>
<% end %>

<br />

<%= link_to '<i class="icon-plus-sign"></i> New Task'.html_safe, new_task_path, :class => 'btn btn-mini' %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<%= render partial: "task_summary", :locals => { :task => @task } %>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>