config/routes.rb
TimeSquirrel::Application.routes.draw do

  resources :projects
  resources :tasks
  resources :timers, :expect => [:new, :create, :index]
  resources :harvest_projects, :expect => [:new, :create]

  match "daily_total" => "home#daily", :as => :daily

  match "start_timer" => "timers#start_timer", :as => :start_timer
  match "stop_timer"  => "timers#stop_timer",  :as => :stop_timer

  match 'sync_jira_tasks' => "sync#sync_jira_tasks", :as => :sync_jira
  match 'sync_harvest_tasks' => "sync#sync_harvest_tasks", :as => :sync_harvest
  match 'push_harvest_entries' => "sync#push_harvest_entries", :as => :push_harvest_entries

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @total_time = Timer.total_time_this_week
    @week_percent_complete = ((((@total_time/60.0)/60.0) * 85.0)/2500.0)*100
    @total_time_this_month = Timer.total_time_this_month
    @month_percent_complete = ((((@total_time_this_month/60.0)/60.0) * 85.0)/10000.0)*100
  end

  def daily
    @date = params[:day].present? ? Date.parse(params[:day]) : Date.today
    @projects = Project.all
    @total_time = Timer.total_time_on_day(@date)
    @timers = Timer.on_day(@date)
  end

  def weekly
    @projects = Project.all
  end
end

app/helpers/home_helper.rb
module HomeHelper

  def weekly_time_percentage
    percentage = (Time.now - Time.now.at_beginning_of_week)/seconds_per_work_week
    percentage*100
  end

  def seconds_per_work_week
    (60*60*24*5)
  end

  def monthly_time_percentage
    percentage = business_days_to_date/total_business_days_in_month
    percentage*100
  end

  def business_days_to_date
    business_days_between(Date.today.at_beginning_of_month, Date.today).to_f
  end

  def total_business_days_in_month
    business_days_between(Date.today.at_beginning_of_month, Date.today.at_end_of_month).to_f
  end

  def business_days_between(date1, date2)
  business_days = 0
    while date2 > date1
     business_days += 1 unless date2.saturday? or date2.sunday?
     date2 = date2 - 1.day
    end
    business_days
  end

  def ahead_of_monthly_goal?
    @month_percent_complete > monthly_time_percentage
  end

  def ahead_of_weekly_goal?
    @week_percent_complete > weekly_time_percentage
  end
end

app/views/home/daily.html.erb
<h3>Total for <%= @date == Date.today ? 'Today' : @date.strftime('%A, %B %e') %></h3>
<div class="row">
  <div class="span9">
    <ul class='timeline'>
    <% @timers.each do |timer| %>
      <li style="width:<%= timer.width %>%;margin-left:<%= timer.offset %>%;">
        <%= link_to '', task_path(timer.task), 'data-toggle' => 'tooltip', 'title' => formatted_duration(timer.time_elapsed) %>
      </li>
    <% end %>
    </ul>
  </div>
</div>
<script type="text/javascript">
  jQuery( function($) {
      $(".timeline li a").tooltip()
  });
</script>
<div class="row">
  <div class="span9">
    <ul class="times">
      <% (1..18).each_with_index do |time, i| %>
        <li style="width:5.56%;margin-left:<%= 5.56 * i %>%;">&nbsp;</li>
      <% end %>
    </ul>
    <ul class="hour_marker">
      <% [6,7,8,9,10,11,'Noon',1,2,3,4,5,6,7,8,9,10,11].each_with_index do |time, i| %>
        <li style="width:5.56%;margin-left:<%= 5.56 * i %>%;"><%= time %></li>
      <% end %>
    </ul>
  </div>
</div>

<div class="row">
  <div class="span3 well">
    <p class='lead'>Total Time: <%= formatted_duration(@total_time) %></p>
  </div>

  <div class="span3 well">
    <p class='lead'>Total Value:  <%= number_to_currency(((@total_time/60.0)/60.0) * 85.0) %></p>
  </div>
</div>

<p><%= link_to 'Push to Harvest', push_harvest_entries_path(:date => @date), :class => 'btn btn-primary'  %></p>

<hr>

<% @projects.each do |project| %>
<% next if project.tasks.with_timers_on_day(@date).blank? %>
  <h3><%= link_to project.title, project_path(project) %> <small><%= project.code %></small></h3>
  <%= render partial: "shared/tasks_table", :locals => { :project => project, :tasks => project.tasks.with_timers_on_day(@date) } %>
  <p>&nbsp;</p>
<% end %>

app/views/home/index.html.erb
<div class="row">
  <div class="span12">
    <h2>Dashboard</h2>
  </div>
</div>

<div class="row">
  <div class="span12">
    <h3>This week:</h3>
  </div>
  <div class="span3 well">
    <p class='lead'>Total Time: <%= formatted_duration(@total_time) %></p>
  </div>

  <div class="span3 well">
    <p class='lead'>Total Value: <%= number_to_currency(((@total_time/60.0)/60.0) * 85.0) %></p>
  </div>

  <div class="span8 well">
    <p class='lead'>Weekly Percent Complete</p>
    <div class='percentage positive' style='width:<%= @week_percent_complete %>%'>
      <span style='padding-left:50%'>
        <%= number_to_percentage(@week_percent_complete, :precision => 0) %>
      </span>
    </div>
    <div class='percentage compare <%= ahead_of_weekly_goal? ? "green" : "red" %>' style='width:<%= weekly_time_percentage %>%'>
      <span style='padding-left:50%'>
        <%= number_to_percentage(weekly_time_percentage, :precision => 0) %>
      </span>
    </div>
  </div>
</div>

<div class="row">
  <div class="span12">
    <h3>This month:</h3>
  </div>

  <div class="span3 well">
    <p class='lead'>Total Time: <%= formatted_duration(@total_time_this_month) %></p>
  </div>

  <div class="span3 well">
    <p class='lead'>Total Value: <%= number_to_currency(((@total_time_this_month/60.0)/60.0) * 85.0) %></p>
  </div>

  <div class="span8 well">
    <p class='lead'>Monthly Percent Complete</p>
    <div class='percentage positive' style='width:<%= @month_percent_complete %>%'>
      <span style='padding-left:50%'>
        <%= number_to_percentage(@month_percent_complete, :precision => 0) %>
      </span>
    </div>
    <div class='percentage compare <%= ahead_of_monthly_goal? ? "green" : "red" %>' style='width:<%= monthly_time_percentage %>%'>
      <span style='padding-left:50%'>
        <%= number_to_percentage(monthly_time_percentage, :precision => 0) %>
      </span>
    </div>
  </div>
</div>