config/routes.rb
TimeSquirrel::Application.routes.draw do

  resources :projects
  resources :tasks
  resources :timers, :expect => [:new, :create, :index]
  resources :harvest_projects, :expect => [:new, :create]

  match "daily_total" => "home#daily", :as => :daily

  match "start_timer" => "timers#start_timer", :as => :start_timer
  match "stop_timer"  => "timers#stop_timer",  :as => :stop_timer

  match 'sync_jira_tasks' => "sync#sync_jira_tasks", :as => :sync_jira
  match 'sync_harvest_tasks' => "sync#sync_harvest_tasks", :as => :sync_harvest
  match 'push_harvest_entries' => "sync#push_harvest_entries", :as => :push_harvest_entries

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  has_one :harvest_project

  attr_accessible :code, :title, :active

  scope :with_tasks, joins(:tasks).group('id')
  scope :active, -> { where('projects.active == ?', true) }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    if params[:show] == 'all'
      @projects = Project.all
      @tasks = Task.all
    elsif params[:show] == 'inactive'
      @projects = Project.with_tasks
      @tasks = Task.all
    else
      @projects = Project.active
      @tasks = Task.active
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    if params[:show] == 'all'
      @tasks = @project.tasks
    else
      @tasks = @project.tasks.active
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        unlinked_project = HarvestProject.without_ts_project

        if unlinked_project.count != 0
          @project = unlinked_project.first
          render edit_project_path(@project)
        else
          format.html { redirect_to @project, notice: 'Project was successfully updated.' }
          format.json { head :no_content }
        end
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :code %>
    <%= f.input :active %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/_tasks_table.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Timer</th>
      <th>Issue</th>
      <th>Summary</th>
      <th>Week</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
    <% next if task.project_id != project.id %>
      <tr>
        <% if task.running_timer? %>
          <td class='timer'><%= link_to '<i class="icon-time"></i> Stop'.html_safe, stop_timer_path(:task_id => task.id), :class => 'btn btn-mini btn-danger' %></td>
        <% else %>
          <td class='timer'><%= link_to '<i class="icon-time"></i> Start'.html_safe, start_timer_path(:task_id => task.id), :class => 'btn btn-mini btn-success' %></td>
        <% end %>
        <td class='issue'><%= task.issue_id.present? ? link_to(task.issue_id, "https://railsdog.atlassian.net/browse/#{task.issue_id}", html_options = {:target => '_blank'}).html_safe : '' %></td>
        <td><%= link_to task.summary, task %></td>
        <td class='timer'><%= formatted_duration(task.timers.total_time_this_week) %></td>
        <td class='task'><%= link_to '<i class="icon-file"></i> '.html_safe, task %></td>
        <td class='task'><%= link_to '<i class="icon-pencil"></i> '.html_safe, edit_task_path(task) %></td>
        <td class='task'><%= link_to '<i class="icon-trash"></i> '.html_safe, task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan='6'>
        <%= link_to 'New Task', new_task_path, :class =>'btn btn-mini' %>
      </td>
    </tr>
  </tfoot>
</table>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<% @projects.each do |project| %>
  <h3><%= link_to project.title, project_path(project) %> <small><%= project.code %></small></h3>

    <%= render partial: "shared/tasks_table", :locals => { :project => project, :tasks => @tasks } %>

<% end %>

<br />

<%= link_to '<i class="icon-plus-sign"></i> New Project'.html_safe, new_project_path, :class => 'btn btn-mini' %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h3><%= @project.title %> <small><%= @project.code %></small></h3>

<%= render partial: "shared/tasks_table", :locals => { :project => @project, :tasks => @tasks } %>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>