config/routes.rb
TimeSquirrel::Application.routes.draw do

  resources :projects
  resources :tasks
  resources :timers, :expect => [:new, :create, :index]
  resources :harvest_projects, :expect => [:new, :create]

  match "daily_total" => "home#daily", :as => :daily

  match "start_timer" => "timers#start_timer", :as => :start_timer
  match "stop_timer"  => "timers#stop_timer",  :as => :stop_timer

  match 'sync_jira_tasks' => "sync#sync_jira_tasks", :as => :sync_jira
  match 'sync_harvest_tasks' => "sync#sync_harvest_tasks", :as => :sync_harvest
  match 'push_harvest_entries' => "sync#push_harvest_entries", :as => :push_harvest_entries

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Time Squirrel", root_path, :class => 'brand' %>
<ul class="nav">

  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>

  <% if user_signed_in? %>
    <li>
      <%= link_to 'Projects', projects_path %>
    </li>
    <li>
      <%= link_to 'Today', daily_path %>
    </li>
  <% end %>
</ul>
<% if Timer.running_timers.present? %>
  <ul class='nav pull-right'>
    <% Timer.running_timers.each do |timer| %>
      <li>
        <%= link_to "<i class='icon-time'></i> <span class='label label-important'>#{formatted_duration(timer.time_elapsed)}</span>".html_safe, project_path(timer.task.project) %>
      </li>
    <% end %>
  </ul>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Time Squirrel" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Time Squirrel" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span9">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well">
                <h3>Quick Links</h3>
                <%= link_to "Sync with Jira", sync_jira_path %> <br>
                <%= link_to "Sync with Harvest", sync_harvest_path %>
                <hr>
                <h4>Daily Totals</h4>
                <p><%= link_to 'Today', daily_path %></p>
                <% (1..6).each do |i| %>
                  <p><%= link_to days_ago(i).strftime('%A'), daily_path(:day => days_ago(i)) %></p>
                <% end %>
              </div>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>